### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Nero0113** [ives-nx/dwk_preprocess#1]
向您请教，这个包下载了之后怎么用呢，我尝试过直接运行也尝试过build，都不太行，第一次接触，望不吝赐教

**Comment by ives-nx** [comment]
这是一个python 脚本
把joern_slicer/joern_parse.py中main函数的root_dir改成你要parse的CPP文件目录(这里只能是fold，不能是file)
然后cd到joern_slicer目录下
运行python joern_parse.py

**Comment by ives-nx** [comment]
joern-parse 你能正常跑起来吗

**Comment by Nero0113** [comment]
> joern-parse 你能正常跑起来吗

对，我现在就是尝试直接控制台./joern-parse，运行不起来，同时跑python joern_parse.py也会卡在`cmd = './joern-parse output/ '+data_path`

**Comment by Nero0113** [comment]
> 这个joern好像缺少一些东西，我重新上传一个

非常感谢您的帮助，祝您工作顺利

**Comment by ives-nx** [comment]
方便留个邮箱吗，我先给你发过去吧，这个我后续更新

**Comment by Nero0113** [comment]
> 方便留个邮箱吗，我先给你发过去吧，这个我后续更新

非常方便哈哈哈，lidong@cqu.edu.cn，再次感谢🙏

**Comment by ives-nx** [comment]
已补发，请查收

**Comment by Nero0113** [comment]
> 已补发，请查收

感谢您的帮助，我这边已经可以运行并得出edges.csv和nodes.csv了，虽然不知道和基线得出的是否一致，但好在不会报错了
